apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: watchlisttracker
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8000
          - path: /api/test
            pathType: Prefix
            backend:
              service:
                name: test-service
                port:
                  number: 8501