spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: user
          uri: lb://user
          predicates:
            - Path=/users/**
          # filters:
          #   - RewritePath=/users/(?<path>.*), /$\{path}
        - id: collablist
          uri: lb://collablist
          predicates:
            - Path=/friendswatchlists/**
          filters:
            - RewritePath=/friendswatchlists/(?<path>.*), /$\{path}
        - id: mediastats
          uri: lb://mediastats
          predicates:
            - Path=/mediastatistics/**
          filters:
            - RewritePath=/mediastatistics/(?<path>.*), /$\{path}
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS