spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: organization
          uri: lb://organization
          predicates:
            - Path=/organizations/**
          filters:
            - RewritePath=/organizations/(?<path>.*), /$\{path}
        - id: test
          uri: lb://test
          predicates:
            - Path=/test/**
          filters:
            - RewritePath=/test/(?<path>.*), /$\{path}
        - id: user
          uri: lb://user
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"