spring:
  application:
    name: organization
  data:
    mongodb:
      uri: mongodb+srv://admin-user:IldownVlfUPbyFtE@user-repository.z68aw.mongodb.net/organization-database?retryWrites=true&w=majority
      database: organization-database
      # uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb/${MONGO_DATABASE}
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS