name: CD

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-to-okteto:
    runs-on: ubuntu-latest
    steps:
      - name: "Push changes"
        uses: okteto/push@latest
        with:
          namespace: polishedstudios
          name: watchlisttracker
