name: CD

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-to-okteto:
    runs-on: ubuntu-latest
    steps:
      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
    
      - name: "Activate Namespace"
        uses: okteto/namespace@latest
        with:
          name: polishedstudios
          
      - name: "Build admin-service"
        uses: okteto/build@latest
        with:
          path: admin-service
          file: Dockerfile
    
      - name: "Deploy application"
        uses: okteto/apply@latest
        with:
          namespace: polishedstudios
          manifest: k8s
        
      - name: "Push changes"
        uses: okteto/push@latest
        with:
          namespace: polishedstudios
          name: watchlisttracker
